export const operator = {
  company: 'SKYWIND SOUTH AFRICA (PTY) LTD',
  representative: 'Prof. Wolfgang Zivny, Director / CEO',
  email: 'info@bonanza-ranch.com',
  address: 'c/o Jordaan, Van Wyk Attorneys Inc.<br>65 Main Service Road<br>6573 Sedgefield, Western Cape<br>South Africa',
};

const contact = `<address><strong>${operator.company}</strong><br>${operator.representative}<br>${operator.address}<br><a href="mailto:${operator.email}">${operator.email}</a></address>`;
type Section = { title: string; html: string };

export const imprint: Record<string, Section[]> = {
  de: [
    { title: 'Anbieter & Kontakt', html: `<p>BONANZA RANCH ECO WILDLIFE ESTATE</p>${contact}<p>Weitere Kontaktadresse: <a href="mailto:info@skywind.co.za">info@skywind.co.za</a></p>` },
    { title: 'Register & Steuerangaben', html: '<p>Register: Companies and Intellectual Property Commission (CIPC), Republic of South Africa, Pretoria.<br>Registereintrag: 871243/07<br>Weitere CIPC-Referenz: 9465422584<br>Umsatzsteuer-ID laut Betreiberangaben: 9700917199</p><p>Register- und Aufsichtsbehörde: <a href="https://www.cipc.co.za/">Companies and Intellectual Property Commission of South Africa</a>.</p>' },
    { title: 'Zum Projekt', html: '<p>Diese Website informiert über das Entwicklungsvorhaben Bonanza Ranch Eco Wildlife Estate. Sie ist kein Verkaufsprospekt und kein verbindliches Angebot zum Erwerb von Grundstücken.</p><p>Beschriebene Anlagen, Leistungen und Ausstattungen geben den Planungsstand wieder. Konzeptbilder veranschaulichen eine mögliche Gestaltung. Planung, Genehmigungen und Umsetzung können sich ändern.</p>' },
    { title: 'Inhalte & Bildmaterial', html: '<p>Texte, Gestaltung, Fotografien, Filme und Visualisierungen sind urheberrechtlich geschützt, soweit die gesetzlichen Voraussetzungen vorliegen. Eine Nutzung außerhalb gesetzlicher Erlaubnisse setzt die Zustimmung der jeweiligen Rechteinhaber voraus.</p><p>Als Konzeptvisualisierung gekennzeichnete Bilder wurden zur Darstellung geplanter Bereiche erstellt. Die geografische Karte dient der Orientierung; die Reiseroute ist schematisch. Sie stellt keine Grundstücksgrenze dar.</p>' },
  ],
  en: [
    { title: 'Provider & contact', html: `<p>BONANZA RANCH ECO WILDLIFE ESTATE</p>${contact}<p>Additional contact: <a href="mailto:info@skywind.co.za">info@skywind.co.za</a></p>` },
    { title: 'Registration & tax details', html: '<p>Register: Companies and Intellectual Property Commission (CIPC), Republic of South Africa, Pretoria.<br>Registration entry: 871243/07<br>Additional CIPC reference: 9465422584<br>VAT identifier as supplied by the operator: 9700917199</p><p>Registration and supervisory authority: <a href="https://www.cipc.co.za/">Companies and Intellectual Property Commission of South Africa</a>.</p>' },
    { title: 'About the project', html: '<p>This website presents Bonanza Ranch Eco Wildlife Estate as a project in development. It is neither a sales prospectus nor a binding offer to purchase land.</p><p>Facilities, services and amenities described reflect the planning stage. Concept images illustrate possible designs. Plans, approvals and implementation may change.</p>' },
    { title: 'Content & imagery', html: '<p>Text, design, photographs, films and visualisations are protected by copyright where applicable. Use beyond statutory permissions requires consent from the relevant rights holders.</p><p>Images labelled as concept visualisations illustrate planned areas. The geographic map provides orientation and the route is schematic. It does not indicate property boundaries.</p>' },
  ],
};

export const privacy: Record<string, Section[]> = {
  de: [
    { title: 'Verantwortlicher', html: `<p>Für die Verarbeitung personenbezogener Daten auf dieser Website ist verantwortlich:</p>${contact}<p>Bei Fragen zum Datenschutz können Sie sich an die oben genannte E-Mail-Adresse wenden. Diese Erklärung beschreibt die Website und ihre Kontaktmöglichkeiten, nicht mögliche spätere Leistungen des Estate.</p>` },
    { title: 'Websitebetrieb & Hosting', html: '<p>Die öffentliche Website wird über Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, USA, ausgeliefert. Beim Abruf fallen technisch notwendige Daten an, etwa IP-Adresse, Zeitpunkt, angefragte URL, Referrer, Browser- und Betriebssysteminformationen sowie Status- und Fehlerdaten.</p><p>Wir benötigen diese Verarbeitung zur Bereitstellung, Fehlerbehebung und Absicherung der Website. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse ist ein verlässlicher und sicherer Betrieb. Technische Protokolldaten werden zweckgebunden und nur so lange verarbeitet, wie dies für Betrieb, Sicherheit und gegebenenfalls die Klärung von Vorfällen erforderlich ist.</p><p>Vercel verarbeitet Daten auch außerhalb des Europäischen Wirtschaftsraums. Nach eigenen Angaben nutzt Vercel das EU-U.S. Data Privacy Framework und, soweit einschlägig, Standardvertragsklauseln. Angaben zu Empfängern und Schutzmaßnahmen finden Sie in der <a href="https://vercel.com/legal/privacy-notice">Vercel-Datenschutzerklärung</a> und im <a href="https://vercel.com/legal/dpa">Data Processing Addendum</a>.</p>' },
    { title: 'Automatische Sprachauswahl', html: '<p>Beim Aufruf der Startadresse nutzt die Website die von Vercel aus der IP-Adresse ermittelte Länderkennung. Für Deutschland wird Deutsch angeboten, für andere Länder Englisch. Es werden weder GPS-Daten abgefragt noch Bewegungsprofile erstellt. Die Anwendung speichert die Länderkennung nicht.</p><p>Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Unser Interesse ist die verständliche Darstellung der Website. Eine Länderkennung kann etwa bei VPN-Nutzung abweichen. Über DE / EN können Sie die Sprache jederzeit selbst wählen; diese Auswahl hat Vorrang vor der automatischen Zuordnung.</p>' },
    { title: 'Cookies & lokaler Speicher', html: '<p>Die Website bindet keine Analyse- oder Werbedienste ein. Insbesondere sind Google Analytics, Vercel Web Analytics und Werbepixel nicht eingebaut.</p><ul><li><strong>bonanza_language:</strong> Ein Cookie speichert ausschließlich Ihre manuelle Wahl „de“ oder „en“ für höchstens 180 Tage. Es wird erst beim Anklicken einer Sprachwahl gesetzt.</li><li><strong>bonanza_cookie_notice:</strong> Der lokale Browserspeicher merkt sich nach „Verstanden“, dass Sie den Cookie-Hinweis geschlossen haben. Gespeichert werden Versionsstand und Zeitpunkt. Der Eintrag wird höchstens 180 Tage zur Unterdrückung des Hinweises verwendet und bei Ablauf beim nächsten Besuch entfernt. Er wird nicht an den Server übermittelt.</li></ul><p>Diese Speicherungen dienen den von Ihnen gewählten Funktionen. Grundlage für den Zugriff auf Ihr Endgerät ist § 25 Abs. 2 Nr. 2 TDDDG; soweit personenbezogene Daten betroffen sind, Art. 6 Abs. 1 lit. f DSGVO. Sie können die Einträge über Ihre Browsereinstellungen löschen. Über „Cookie-Einstellungen“ im Footer lässt sich der Hinweis erneut öffnen. Ohne Speicherung bleibt die Website nutzbar; Hinweise oder die automatische Sprachwahl können erneut erscheinen.</p>' },
    { title: 'E-Mail-Kontakt', html: '<p>Die Kontaktlinks öffnen Ihr E-Mail-Programm. Die Website selbst versendet kein Kontaktformular. Erst wenn Sie Ihre Nachricht absenden, erhalten wir Ihre Absenderadresse, den Inhalt und weitere von Ihnen übermittelte Angaben. Empfänger ist die oben genannte Projektgesellschaft in Südafrika; zur Zustellung sind die beteiligten E-Mail-Dienste eingebunden.</p><p>Die Angaben werden zur Bearbeitung Ihrer Anfrage genutzt. Bei vertragsbezogenen Anfragen gilt Art. 6 Abs. 1 lit. b DSGVO; ansonsten Art. 6 Abs. 1 lit. f DSGVO, gestützt auf unser Interesse an der Beantwortung Ihrer Nachricht. Eine Anfrage ist keine Newsletter-Anmeldung.</p><p>Wir löschen Anfragedaten, wenn die Bearbeitung abgeschlossen ist und keine gesetzlichen Aufbewahrungspflichten, Vertragsbeziehungen oder berechtigten Nachweisinteressen eine weitere Speicherung erfordern. Die Nachricht wird in Südafrika bearbeitet. Die für eine direkte Anfrage erforderlichen Angaben stellen Sie dem dortigen Verantwortlichen selbst zur Verfügung.</p>' },
    { title: 'Bilder, Videos, Schriften & Links', html: '<p>Bilder, Videos, Schriftdateien und die Kartenabbildung werden über dieselbe Website bereitgestellt. Es gibt keine eingebetteten YouTube-Player, Google-Fonts-Aufrufe, Google-Maps-Widgets oder Social-Media-Feeds. Die Darstellung dieser Medien löst keine zusätzlichen Anfragen an solche Anbieter aus.</p><p>Externe Quellen sind als Links erreichbar. Erst beim Öffnen eines solchen Links wird die jeweilige Website besucht. Für deren Verarbeitung ist der jeweilige Anbieter verantwortlich.</p>' },
    { title: 'Ihre Datenschutzrechte', html: '<p>Soweit die DSGVO anwendbar ist, haben Sie nach ihren Voraussetzungen Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Sie können aus Gründen Ihrer besonderen Situation einer auf Art. 6 Abs. 1 lit. f DSGVO beruhenden Verarbeitung widersprechen. Eine erteilte Einwilligung können Sie jederzeit für die Zukunft widerrufen.</p><p>Wenden Sie sich hierzu an <a href="mailto:info@bonanza-ranch.com">info@bonanza-ranch.com</a>. Zudem können Sie sich bei einer zuständigen Datenschutzaufsichtsbehörde beschweren, insbesondere am Ort Ihres gewöhnlichen Aufenthalts, Ihres Arbeitsplatzes oder eines mutmaßlichen Verstoßes. Für Südafrika ist der <a href="https://inforegulator.org.za/contact-us/">Information Regulator</a> erreichbar; Rechte nach dem südafrikanischen Protection of Personal Information Act (POPIA) bleiben unberührt.</p><p>Die Bereitstellung von Kontaktdaten ist freiwillig. Ohne die für eine Antwort erforderlichen Angaben können wir eine Anfrage gegebenenfalls nicht bearbeiten. Über diese Website findet keine automatisierte Entscheidung mit rechtlicher oder vergleichbarer erheblicher Wirkung statt.</p>' },
  ],
  en: [
    { title: 'Data controller', html: `<p>The controller responsible for personal data on this website is:</p>${contact}<p>Please contact the email address above with privacy questions. This notice covers this website and its contact channels, rather than any future services at the estate.</p>` },
    { title: 'Website operation & hosting', html: '<p>The public website is delivered by Vercel Inc., 440 N Barranca Avenue #4133, Covina, CA 91723, USA. Requests involve technical information including IP address, time, requested URL, referrer, browser and operating system details, status codes and errors.</p><p>This processing enables delivery, troubleshooting and security. Where the GDPR applies, the basis is Article 6(1)(f), reflecting our legitimate interest in reliable, secure operation. Technical logs are processed only for as long as necessary for these purposes and, where relevant, investigating incidents.</p><p>Vercel also processes data outside the European Economic Area. It states that it relies on the EU-U.S. Data Privacy Framework and, where applicable, Standard Contractual Clauses. Further details are in the <a href="https://vercel.com/legal/privacy-notice">Vercel Privacy Notice</a> and <a href="https://vercel.com/legal/dpa">Data Processing Addendum</a>.</p>' },
    { title: 'Automatic language selection', html: '<p>When you visit the entry URL, the website uses the country code Vercel derives from your IP address. Germany receives German; other countries receive English. No GPS permission is requested and no movement profile is created. The application does not store the country code.</p><p>The GDPR basis is Article 6(1)(f), our legitimate interest in presenting understandable content. A VPN may affect country detection. You can choose DE / EN at any time; a manual choice takes priority.</p>' },
    { title: 'Cookies & local storage', html: '<p>No analytics or advertising services are embedded. Google Analytics, Vercel Web Analytics and advertising pixels are not installed.</p><ul><li><strong>bonanza_language:</strong> This cookie remembers only a manual choice of “de” or “en” for up to 180 days. It is set when you click a language choice.</li><li><strong>bonanza_cookie_notice:</strong> After you click “Understood”, local browser storage records the version and dismissal time of the notice. The entry is used for up to 180 days and removed on the next visit after expiry. It is not sent to the server.</li></ul><p>These entries support functions you have selected. Where applicable, device storage relies on Section 25(2)(2) TDDDG and processing of personal data on Article 6(1)(f) GDPR. You can delete entries using your browser settings and reopen the notice through “Cookie settings” in the footer. The website remains usable without storage, but the notice or automatic language choice may reappear.</p>' },
    { title: 'Email enquiries', html: '<p>Contact links open your email application. This website does not submit a contact form. When you send an email, we receive your address, message and any other details you include. The recipient is the project company identified above in South Africa; the email providers involved also handle delivery.</p><p>We use this information to respond. The GDPR basis is Article 6(1)(b) for contract-related enquiries and Article 6(1)(f) for other correspondence, reflecting our legitimate interest in answering you. An enquiry does not subscribe you to a newsletter.</p><p>Enquiry data is deleted when correspondence is complete unless retention obligations, ongoing contracts or legitimate evidential needs require it to be kept. Your message is handled in South Africa. You provide the information necessary for a direct enquiry to the controller there.</p>' },
    { title: 'Media, fonts & external links', html: '<p>Images, videos, fonts and the map image are delivered through this website. There are no embedded YouTube players, Google Fonts requests, Google Maps widgets or social feeds. Displaying these media does not create additional requests to those providers.</p><p>External sources are provided as links. Visiting one opens that provider’s website, where its own privacy terms apply.</p>' },
    { title: 'Your privacy rights', html: '<p>Where the GDPR applies, you may request access, correction, deletion, restriction and data portability, subject to its conditions. You may object, for reasons relating to your particular situation, to processing based on Article 6(1)(f). Any consent may be withdrawn for the future.</p><p>Contact <a href="mailto:info@bonanza-ranch.com">info@bonanza-ranch.com</a>. You may also complain to a competent data protection authority, particularly where you normally reside, work or believe an infringement occurred. In South Africa, you can contact the <a href="https://inforegulator.org.za/contact-us/">Information Regulator</a>. Rights under the Protection of Personal Information Act (POPIA) remain unaffected.</p><p>Providing contact details is voluntary. Without the information needed to respond, we may be unable to answer an enquiry. This website does not make automated decisions producing legal or similarly significant effects.</p>' },
  ],
};
